### ISSUE TITLE
Exception thrown when Row ID does not exist

### ISSUE THREAD

**Issue by BartChris** [rafaelnajera/datatable#2]
In the getRow()-method of the MySQL-DataTable-Class, the associative Array is fetched immediately after retrieval of the dataset: 

https://github.com/rafaelnajera/datatable/blob/master/DataTable/MySqlDataTable.php#L194

This is a problem, when the row with the specified ID does not exist and the mysqli execution only returns TRUE.
See: 
http://www.php.net/manual/en/mysqli.query.php
"Returns FALSE on failure. For successful SELECT, SHOW, DESCRIBE or EXPLAIN queries mysqli_query() will return a mysqli_result object. For other successful queries mysqli_query() will return TRUE. "

In that case, we get a Slim Error:

Call to a member function fetch() on boolean
File: /home/christoph/DARE/DARE_Management/public/vendor/rafaelnajera/datatable/DataTable/MySqlDataTable.php
Line: 199

We should probably also count the rows using 
mysqli_num_rows($result)

**Comment by rafaelnajera** [comment]
Taken care of in version 0.5
